# Exported from Render on 2025-03-05T01:32:46Z
services:
- type: web
  name: n8n_test
  runtime: node
  repo: https://github.com/n8n-io/n8n
  plan: free
  envVars:
  - key: NODE_VERSION
    sync: false
  - key: WEBHOOK_URL
    sync: false
  - key: WEBHOOK_TUNNEL_URL
    sync: false
  - key: N8N_PROTOCOL
    sync: false
  - key: N8N_PORT
    sync: false
  - key: N8N_HOST
    sync: false
  region: frankfurt
  buildCommand: pnpm install --frozen-lockfile; pnpm run build
  startCommand: pnpm run start
version: "1"
